// Writes motion.css: motion.base.css plus every wibblet's two masks as
// data URIs. Inline, because a mask image from another origin needs CORS
// and a film opened from disk has no origin at all.
// Usage: node kit/tools/art.mjs   (from anywhere)
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const kit = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const uri = f => `url(data:image/png;base64,${readFileSync(path.join(kit, "art", f)).toString("base64")})`;
const names = readdirSync(path.join(kit, "art")).filter(f => f.startsWith("body-")).map(f => f.slice(5, -4)).sort();
const rules = names.map(n => `.mo-wb[data-l="${n}"]{--mo-body:${uri(`body-${n}.png`)};--mo-face:${uri(`face-${n}.png`)}}`);
writeFileSync(path.join(kit, "motion.css"), readFileSync(path.join(kit, "motion.base.css"), "utf8") +
  "\n/* ---------- art: generated by tools/art.mjs ---------- */\n" + rules.join("\n") + "\n");
console.log(`motion.css: ${names.length} wibblets`);
